<h1> Dora the explorer

In [1]:
%load_ext autoreload

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', None)

In [3]:
%autoreload
import sys
from pipeline import Pipeline as Pipin
pipe = Pipin()

Current working directory: /Users/matsalexander/Desktop/Forest Gump/mats

In [4]:
# all_data = pipe.get_combined_datasets(offset_years=True)
all_data = pipe.get_combined_data()
df0 = all_data

Se p√• features

In [5]:
snow_features = [c  for c in all_data.columns if 'snow' in c]
snow_features
all_data[snow_features].describe()

,fresh_snow_12h:cm,fresh_snow_1h:cm,fresh_snow_24h:cm,fresh_snow_3h:cm,fresh_snow_6h:cm,snow_density:kgm3,snow_depth:cm,snow_drift:idx,snow_melt_10min:mm,snow_water:kgm2
count,92951.000000,92951.000000,92951.000000,92951.000000,92951.000000,4213.0,92951.000000,92951.000000,92951.000000,92951.000000
mean,0.117096,0.009727,0.231608,0.029244,0.058533,250.0,0.193164,0.000022,0.000273,0.090299
std,0.779764,0.104943,1.223007,0.275208,0.477040,0.0,1.253925,0.004181,0.004249,0.237841
min,0.000000,0.000000,0.000000,0.000000,0.000000,250.0,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,250.0,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,250.0,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,250.0,0.000000,0.000000,0.000000,0.100000
max,37.474998,7.250000,37.474998,20.325001,33.375000,250.0,18.200001,1.000000,0.180000,5.650000

In [6]:
for sne_feat in snow_features:
    sne_sum = all_data[sne_feat].sum()
    print(f'{sne_feat} : {sne_sum} ')

fresh_snow_12h:cm : 10884.2001953125
fresh_snow_1h:cm : 904.1250610351562
fresh_snow_24h:cm : 21528.17578125
fresh_snow_3h:cm : 2718.25
fresh_snow_6h:cm : 5440.69970703125
snow_density:kgm3 : 1053250.0
snow_depth:cm : 17954.826171875
snow_drift:idx : 2.0
snow_melt_10min:mm : 25.399999618530273
snow_water:kgm2 : 8393.375

In [7]:
sum_snow_drift = all_data['snow_drift:idx'].sum()
sum_snow_drift

2.0

<h1>New groupe<h1>

In [8]:
%autoreload
import sys
from pipeline_new_group import Pipeline as Pipin
pipe2 = Pipin()

Current working directory: /Users/matsalexander/Desktop/Forest Gump/mats

In [9]:
df1, Y = pipe2.get_training_data_by_location("A")
df1["date_forecast"] = pd.to_datetime(df1["date_forecast"])
df1[df1["date_forecast"] < "2023-04-30 20:00:00"].tail(20)

,date_forecast,absolute_humidity_2m:gm3,air_density_2m:kgm3,ceiling_height_agl:m,clear_sky_energy_1h:J,clear_sky_rad:W,cloud_base_agl:m,dew_or_rime:idx,dew_point_2m:K,diffuse_rad:W,diffuse_rad_1h:J,direct_rad:W,direct_rad_1h:J,effective_cloud_cover:p,elevation:m,fresh_snow_12h:cm,fresh_snow_1h:cm,fresh_snow_24h:cm,fresh_snow_3h:cm,fresh_snow_6h:cm,is_day:idx,is_in_shadow:idx,msl_pressure:hPa,precip_5min:mm,precip_type_5min:idx,pressure_100m:hPa,pressure_50m:hPa,prob_rime:p,rain_water:kgm2,relative_humidity_1000hPa:p,sfc_pressure:hPa,snow_density:kgm3,snow_depth:cm,snow_drift:idx,snow_melt_10min:mm,snow_water:kgm2,sun_azimuth:d,sun_elevation:d,super_cooled_liquid_water:kgm2,t_1000hPa:K,total_cloud_cover:p,visibility:m,wind_speed_10m:ms,wind_speed_u_10m:ms,wind_speed_v_10m:ms,wind_speed_w_1000hPa:ms,date_calc
136209,2023-04-30 15:00:00,4.6,1.263,4795.500000,1.870634e+06,463.100006,715.400024,0.0,272.799988,164.800003,679038.000000,178.399994,612584.625000,87.900002,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.200012,0.0,0.0,1001.000000,1007.200012,0.0,0.0,66.099998,1013.400024,NaN,0.0,0.0,-0.0,0.0,245.445999,27.790001,0.0,276.700012,87.900002,22850.900391,7.0,7.0,0.4,-0.0,2023-04-29 07:00:05
136210,2023-04-30 15:15:00,4.6,1.264,4181.000000,1.769851e+06,432.500000,708.599976,0.0,272.600006,160.300003,632067.625000,165.600006,629414.187500,86.000000,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.299988,0.0,0.0,1001.099976,1007.299988,0.0,0.0,65.800003,1013.500000,NaN,0.0,0.0,-0.0,0.0,249.139999,26.239000,0.0,276.600006,86.000000,23263.199219,7.0,7.0,0.4,-0.0,2023-04-29 07:00:05
136211,2023-04-30 15:30:00,4.5,1.265,3566.500000,1.664340e+06,401.000000,701.700012,0.0,272.500000,154.500000,583870.625000,152.699997,639885.875000,84.000000,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.299988,0.0,0.0,1001.099976,1007.299988,0.0,0.0,65.400002,1013.500000,NaN,0.0,0.0,-0.0,0.0,252.764999,24.650000,0.0,276.500000,84.000000,23672.000000,7.1,7.1,0.4,-0.0,2023-04-29 07:00:05
136212,2023-04-30 15:45:00,4.5,1.265,2952.000000,1.554693e+06,368.600006,694.799988,0.0,272.299988,146.699997,566436.187500,135.899994,588136.812500,82.199997,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.299988,0.0,0.0,1001.099976,1007.299988,0.0,0.0,65.000000,1013.500000,NaN,0.0,0.0,-0.0,0.0,256.325989,23.030001,0.0,276.500000,82.199997,24077.500000,7.2,7.2,0.4,-0.0,2023-04-29 07:00:05
136213,2023-04-30 16:00:00,4.4,1.266,2337.500000,1.441550e+06,335.700012,687.900024,0.0,272.200012,137.899994,544752.875000,119.800003,536708.875000,80.300003,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.400024,0.0,0.0,1001.200012,1007.299988,0.0,0.0,64.599998,1013.599976,NaN,0.0,0.0,-0.0,0.0,259.832001,21.385000,0.0,276.399994,80.300003,24479.500000,7.2,7.2,0.4,-0.0,2023-04-29 07:00:05
136214,2023-04-30 16:15:00,4.5,1.267,2235.500000,1.325600e+06,302.399994,667.400024,0.0,272.299988,128.000000,518955.687500,104.300003,485907.687500,82.300003,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.400024,0.0,0.0,1001.200012,1007.400024,0.0,0.0,66.000000,1013.599976,NaN,0.0,0.0,-0.0,0.0,263.287994,19.722000,0.0,276.200012,82.300003,23630.800781,7.1,7.0,0.5,-0.0,2023-04-29 07:00:05
136215,2023-04-30 16:30:00,4.5,1.268,2133.399902,1.207590e+06,269.000000,646.900024,0.0,272.399994,117.300003,489243.000000,89.599998,436038.687500,84.199997,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.400024,0.0,0.0,1001.200012,1007.400024,0.0,0.0,67.500000,1013.599976,NaN,0.0,0.0,-0.0,0.0,266.701996,18.047001,0.0,276.100006,84.199997,22788.699219,6.9,6.8,0.6,-0.0,2023-04-29 07:00:05
136216,2023-04-30 16:45:00,4.5,1.269,2031.400024,1.088337e+06,235.699997,626.400024,0.0,272.500000,105.300003,453580.093750,79.900002,388476.406250,86.000000,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.400024,0.0,0.0,1001.200012,1007.400024,0.0,0.0,68.900002,1013.700012,NaN,0.0,0.0,-0.0,0.0,270.079987,16.365999,0.0,276.000000,86.000000,21953.300781,6.7,6.7,0.7,-0.0,2023-04-29 07:00:05
136217,2023-04-30 17:00:00,4.6,1.270,1929.300049,9.687359e+05,203.000000,605.900024,0.0,272.500000,92.800003,415135.406250,69.900002,341525.593750,87.599998,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.400024,0.0,0.0,1001.200012,1007.500000,0.0,0.0,70.300003,1013.700012,NaN,0.0,0.0,-0.0,0.0,273.428986,14.686000,0.0,275.899994,87.599998,21124.900391,6.5,6.5,0.8,-0.0,2023-04-29 07:00:05
136218,2023-04-30 17:15:00,4.6,1.271,1982.099976,8.497867e+05,171.000000,590.000000,0.0,272.500000,79.900002,374361.812500,59.900002,295599.312500,88.000000,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.400024,0.0,0.0,1001.299988,1007.500000,0.0,0.0,70.699997,1013.700012,NaN,0.0,0.0,-0.0,0.0,276.756012,13.011000,0.0,275.799988,88.000000,21071.199219,6.3,6.3,1.0,-0.0,2023-04-29 07:00:05
136219,2023-04-30 17:30:00,4.6,1.272,2034.900024,7.326193e+05,140.300003,574.099976,0.0,272.500000,67.000000,331827.312500,49.900002,251156.703125,88.400002,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.500000,0.0,0.0,1001.299988,1007.500000,0.0,0.0,71.099998,1013.700012,NaN,0.0,0.0,-0.0,0.0,280.066986,11.348000,0.0,275.700012,88.400002,21019.900391,6.2,6.1,1.3,-0.0,2023-04-29 07:00:05
136220,2023-04-30 17:45:00,4.6,1.272,2087.800049,6.185347e+05,111.199997,558.200012,0.0,272.500000,55.299999,289022.500000,31.299999,200138.203125,88.900002,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.500000,0.0,0.0,1001.299988,1007.500000,0.0,0.0,71.500000,1013.799988,NaN,0.0,0.0,-0.0,0.0,283.367004,9.702000,0.0,275.600006,88.900002,20971.199219,6.0,5.8,1.5,-0.0,2023-04-29 07:00:05
136221,2023-04-30 18:00:00,4.6,1.273,2140.600098,5.090587e+05,84.500000,542.299988,0.0,272.500000,43.599998,245497.406250,17.500000,157368.203125,89.500000,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.500000,0.0,0.0,1001.299988,1007.500000,0.0,0.0,72.000000,1013.799988,NaN,0.0,0.0,-0.0,0.0,286.661987,8.078000,0.0,275.500000,89.500000,20925.300781,5.9,5.6,1.7,-0.0,2023-04-29 07:00:05
136222,2023-04-30 18:15:00,4.6,1.274,2013.699951,4.060036e+05,60.799999,543.599976,0.0,272.500000,32.599998,202489.093750,8.100000,122321.296875,91.300003,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.599976,0.0,0.0,1001.400024,1007.599976,0.0,0.0,72.300003,1013.799988,NaN,0.0,0.0,-0.0,0.0,289.958008,6.482000,0.0,275.399994,91.300003,22094.800781,5.7,5.5,1.7,-0.0,2023-04-29 07:00:05
136223,2023-04-30 18:30:00,4.6,1.274,1886.800049,3.115092e+05,40.900002,544.900024,0.0,272.500000,22.700001,161473.593750,2.400000,94154.296875,93.500000,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.599976,0.0,0.0,1001.400024,1007.700012,0.0,0.0,72.699997,1013.900024,NaN,0.0,0.0,-0.0,0.0,293.260010,4.919000,0.0,275.299988,93.500000,23263.000000,5.6,5.4,1.8,-0.0,2023-04-29 07:00:05
136224,2023-04-30 18:45:00,4.6,1.275,1759.900024,2.279455e+05,25.299999,546.200012,0.0,272.500000,15.300000,127061.398438,1.100000,58343.398438,96.000000,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.700012,0.0,0.0,1001.500000,1007.700012,0.0,0.0,73.099998,1014.000000,NaN,0.0,0.0,-0.0,0.0,296.571991,3.394000,0.0,275.299988,96.000000,24430.599609,5.5,5.2,1.8,-0.0,2023-04-29 07:00:05
136225,2023-04-30 19:00:00,4.6,1.275,1633.000000,1.573198e+05,13.500000,547.500000,0.0,272.500000,8.900000,94492.000000,0.400000,32192.599609,98.800003,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1014.700012,0.0,0.0,1001.500000,1007.799988,0.0,0.0,73.500000,1014.000000,NaN,0.0,0.0,-0.0,0.0,299.898987,1.913000,0.0,275.200012,98.800003,25598.000000,5.4,5.1,1.8,-0.0,2023-04-29 07:00:05
136226,2023-04-30 19:15:00,4.6,1.276,1660.500000,9.980430e+04,3.400000,544.299988,0.0,272.500000,2.400000,62895.199219,0.000000,14495.099609,97.099998,6.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1014.700012,0.0,0.0,1001.599976,1007.799988,0.0,0.0,74.199997,1014.000000,NaN,0.0,0.0,-0.0,0.0,303.243988,0.480000,0.0,275.100006,97.099998,24159.300781,5.3,4.9,1.9,-0.0,2023-04-29 07:00:05
136227,2023-04-30 19:30:00,4.5,1.277,1687.900024,5.468290e+04,0.000000,541.099976,0.0,272.399994,0.000000,40799.500000,0.000000,4258.399902,95.900002,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1014.799988,0.0,0.0,1001.599976,1007.799988,0.0,0.0,75.000000,1014.099976,NaN,0.0,0.0,-0.0,0.0,306.610992,-0.898000,0.0,275.000000,95.900002,22691.800781,5.1,4.7,2.0,-0.0,2023-04-29 07:00:05
136228,2023-04-30 19:45:00,4.5,1.278,1715.400024,2.605280e+04,0.000000,537.900024,0.0,272.299988,0.000000,27537.500000,0.000000,1976.500000,95.000000,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1014.799988,0.0,0.0,1001.599976,1007.799988,0.0,0.0,75.800003,1014.099976,NaN,0.0,0.0,-0.0,0.0,310.002991,-2.217000,0.0,274.799988,95.000000,21219.199219,4.9,4.5,2.0,-0.0,2023-04-29 07:00:05

In [10]:
gruped = pipe2.grouped_by_hour_old(df1.copy())
# gruped["date_forecast"] = gruped["date_forecast"].dt.to_timestamp()

for col in gruped.columns:
    if "date_calc" in col[0]:
        print(col)
gruped.tail(10)

,date_forecast,absolute_humidity_2m:gm3,air_density_2m:kgm3,ceiling_height_agl:m,clear_sky_energy_1h:J,clear_sky_rad:W,cloud_base_agl:m,dew_or_rime:idx,dew_point_2m:K,diffuse_rad:W,diffuse_rad_1h:J,direct_rad:W,direct_rad_1h:J,effective_cloud_cover:p,elevation:m,fresh_snow_12h:cm,fresh_snow_1h:cm,fresh_snow_24h:cm,fresh_snow_3h:cm,fresh_snow_6h:cm,is_day:idx,is_in_shadow:idx,msl_pressure:hPa,precip_5min:mm,precip_type_5min:idx,pressure_100m:hPa,pressure_50m:hPa,prob_rime:p,rain_water:kgm2,relative_humidity_1000hPa:p,sfc_pressure:hPa,snow_density:kgm3,snow_depth:cm,snow_drift:idx,snow_melt_10min:mm,snow_water:kgm2,sun_azimuth:d,sun_elevation:d,super_cooled_liquid_water:kgm2,t_1000hPa:K,total_cloud_cover:p,visibility:m,wind_speed_10m:ms,wind_speed_u_10m:ms,wind_speed_v_10m:ms,wind_speed_w_1000hPa:ms
34052,2023-04-30 14:00:00,4.725,1.26275,4965.750000,2.094367e+06,533.125000,736.875000,0.0,273.049988,185.324997,790703.000000,184.899994,529532.000000,90.300003,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,1014.224976,0.0,0.0,1001.000000,1007.200012,0.0,0.0,67.074997,1013.400024,NaN,0.0,0.0,0.0,0.000,235.806503,31.411251,0.000,276.700012,90.300003,21634.275391,6.875,6.875,0.150,0.0
34053,2023-04-30 15:00:00,4.550,1.26425,3873.750000,1.714879e+06,416.299988,705.125000,0.0,272.549988,156.574997,615353.125000,158.149994,617505.375000,85.025002,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,1014.275024,0.0,0.0,1001.074951,1007.275024,0.0,0.0,65.574997,1013.474976,NaN,0.0,0.0,0.0,0.000,250.919250,25.427250,0.000,276.575012,85.025002,23465.900391,7.075,7.075,0.400,0.0
34054,2023-04-30 16:00:00,4.475,1.26750,2184.449951,1.265769e+06,285.700012,657.150024,0.0,272.350006,122.125000,501632.906250,98.400002,461782.906250,83.199997,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,1014.400024,0.0,0.0,1001.200012,1007.375000,0.0,0.0,66.750000,1013.625000,NaN,0.0,0.0,0.0,0.000,264.975494,18.880001,0.000,276.174988,83.199997,23213.074219,6.975,6.925,0.550,0.0
34055,2023-04-30 17:00:00,4.600,1.27125,2008.525024,7.924191e+05,156.375000,582.049988,0.0,272.500000,73.750000,352586.750000,52.750000,272104.937500,88.224998,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,1014.450012,0.0,0.0,1001.275024,1007.500000,0.0,0.0,70.900002,1013.724976,NaN,0.0,0.0,0.0,0.000,278.404755,12.186749,0.000,275.750000,88.224998,21046.800781,6.250,6.175,1.150,0.0
34056,2023-04-30 18:00:00,4.600,1.27400,1950.250000,3.636292e+05,52.875000,544.250000,0.0,272.500000,28.549999,184130.375000,7.275000,108046.796875,92.574997,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,1014.599976,0.0,0.0,1001.400024,1007.625000,0.0,0.0,72.525002,1013.875000,NaN,0.0,0.0,0.0,0.000,291.613007,5.718250,0.000,275.375000,92.574997,22678.425781,5.675,5.425,1.750,0.0
34057,2023-04-30 19:00:00,4.550,1.27650,1674.199951,8.446495e+04,4.225000,542.700012,0.0,272.424988,2.825000,56431.050781,0.100000,13230.649414,96.699997,6.0,0.0,0.0,0.0,0.0,0.0,0.5,0.75,1014.750000,0.0,0.0,1001.574951,1007.799988,0.0,0.0,74.625000,1014.049988,NaN,0.0,0.0,0.0,0.000,304.939240,-0.180500,0.000,275.024994,96.699997,23417.074219,5.175,4.800,1.925,0.0
34058,2023-04-30 20:00:00,4.500,1.27975,1762.400024,2.270875e+03,0.000000,546.400024,0.0,272.299988,0.000000,5067.875000,0.000000,176.350006,94.224998,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,1014.700012,0.0,0.0,1001.549988,1007.799988,0.0,0.0,76.875000,1014.049988,NaN,0.0,0.0,0.0,0.000,318.625763,-5.176000,0.000,274.650024,94.525002,21084.050781,4.650,4.025,2.300,0.0
34059,2023-04-30 21:00:00,4.500,1.28100,1696.650024,0.000000e+00,0.000000,548.349976,0.0,272.299988,0.000000,0.000000,0.000000,0.000000,94.324997,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,1014.549988,0.0,0.0,1001.400024,1007.674988,0.0,0.0,77.775002,1013.925049,NaN,0.0,0.0,0.0,0.000,332.785736,-8.950750,0.000,274.524994,95.675003,20792.500000,4.450,3.575,2.600,0.0
34060,2023-04-30 22:00:00,4.500,1.28100,1353.400024,0.000000e+00,0.000000,527.775024,0.0,272.299988,0.000000,0.000000,0.000000,0.000000,97.775002,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,1014.400024,0.0,0.0,1001.250000,1007.500000,0.0,0.0,79.000000,1013.799988,NaN,0.0,0.0,0.0,0.025,347.377991,-11.233250,0.100,274.325012,98.875000,14158.099609,4.100,3.175,2.550,0.0
34061,2023-04-30 23:00:00,4.500,1.28100,1626.574951,0.000000e+00,0.000000,526.525024,0.0,272.274994,0.000000,0.000000,0.000000,0.000000,98.425003,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,1014.049988,0.0,0.0,1000.875000,1007.099976,0.0,0.0,79.849998,1013.400024,NaN,0.0,0.0,0.0,0.050,92.209503,-11.841500,0.075,274.225006,99.699997,11872.299805,3.750,2.725,2.550,0.0

In [11]:
df = pipe2.get_data("A")
# new_columns = set([col[0] if col[1] % 15 == 0 else col for col in list(df.columns)])
# new_columns

# diff = new_columns.difference (set(df1.columns))
# diff
# df.columns = [str(col) for col in df.columns]
# df['d', 'e', 'h', 'o', 'p']
len(list(df.columns))
see_cols = [ "('snow_density:kgm3', 0)",
 "('snow_density:kgm3', 15)",
 "('snow_density:kgm3', 30)",
 "('snow_density:kgm3', 45)",
 ]
rad_cols = [f"('direct_rad:W', {c})" for c in range(0, 60, 15)]
df["direct_rad:W"] = df[rad_cols].mean(axis=1)
rad_cols.append("direct_rad:W")

df[rad_cols].head()

,"('direct_rad:W', 0)","('direct_rad:W', 15)","('direct_rad:W', 30)","('direct_rad:W', 45)",direct_rad:W
0,0.0,0.0,0.0,0.0,0.00
1,0.0,0.0,0.0,0.0,0.00
2,0.0,0.0,0.0,0.0,0.00
3,0.0,0.0,0.0,0.0,0.00
4,0.0,0.0,0.0,0.6,0.15

In [12]:
dfa = pipe2.get_test_data("A")
# dfa[see_cols].head()

In [13]:
def compare_columns(df1, df2):
    # diff = set(df1.columns).difference(set(df2.columns))
    diff = set(df1.columns)-(set(df2.columns))
    return diff

diff = compare_columns(df, dfa)
diff

{'direct_rad:W', 'pv_measurement'}

In [16]:
cloud_base  = [
    "('cloud_base_agl:m', 0)",
    "('cloud_base_agl:m', 15)",
    "('cloud_base_agl:m', 30)",
    "('cloud_base_agl:m', 45)",
]
sne  = [
    "('snow_drift:idx', 0)",
    "('snow_drift:idx', 15)",
    "('snow_drift:idx', 30)",
    "('snow_drift:idx', 45)",
]

# sne = "snow_drift"
# count nans in each columns 
dfa[cloud_base].isna().sum()

('cloud_base_agl:m', 0)     88
('cloud_base_agl:m', 15)    70
('cloud_base_agl:m', 30)    70
('cloud_base_agl:m', 45)    70
dtype: int64